# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-05 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='demand',
            new_name='requestment',
        ),
    ]
