# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20190409_0951'),
        ('client', '0008_auto_20190409_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
            preserve_default=False,
        ),
    ]
