# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20190409_0951'),
        ('client', '0010_auto_20190410_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='client.OrderItem', to='partner.Menu'),
        ),
    ]
