# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-12 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20190410_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 6, 27, 43, 495936, tzinfo=utc), verbose_name='date_created'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 6, 27, 43, 495936, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
