# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-03 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default=1, max_length=20, verbose_name='연락처'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='demand',
            field=models.CharField(default=2, max_length=30, verbose_name='요청사항'),
            preserve_default=False,
        ),
    ]
