# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20190403_1654'),
        ('client', '0003_auto_20190403_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='client.OrderItem', to='partner.Menu'),
        ),
    ]
