# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20190409_0951'),
        ('client', '0009_auto_20190409_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partner.Menu'),
            preserve_default=False,
        ),
    ]
