# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-12 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20190412_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 7, 42, 27, 659506, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
