# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-12 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20190412_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
