# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-12 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_remove_order_date_created'),
        ('client', '0021_auto_20190412_1522'),
    ]

    operations = [
    ]
