# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-12 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_merge_20190412_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 8, 28, 23, 917435, tzinfo=utc), verbose_name='date_created'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 8, 28, 23, 917435, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
