# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-03 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20190403_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=30, verbose_name='메뉴 이름'),
        ),
    ]
