# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20190403_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='food_categories',
            field=models.CharField(choices=[('KR', 'KOREAN'), ('WE', 'WESTURN'), ('JP', 'JAPANESE'), ('DE', 'DESSERT')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
