# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-09 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20190407_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('KR', '한식'), ('WE', '양식'), ('JP', '일식'), ('DE', '디저트')], max_length=10, verbose_name='카테고리'),
        ),
    ]
